<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan extends CI_Controller{
    function __construct(){
        parent::__construct();
        is_login();
        $this->load->model('Laporan_model');
        $this->load->helper('tgl_indo');
        $this->load->helper('rupiah');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index(){
        $this->form_validation->set_rules('tgl_awal', 'tanggal awal', 'trim|required');
        $this->form_validation->set_rules('tgl_akhir', 'tanggal akhir', 'trim|required');

        if ($this->form_validation->run() == FALSE) {
            $data = array(
                'tgl_awal' => set_value('tgl_awal',date("Y-m-d")),
                'tgl_akhir' => set_value('tgl_akhir',date("Y-m-d")),
                 // 'jadwal' => ''
            );
        }else{
            $data = array(
                'tgl_awal' => $this->input->post('tgl_awal',TRUE),
                'tgl_akhir' => $this->input->post('tgl_akhir',TRUE),

                // 'jadwal' => $this->Booking_model->get_by_date($this->input->post('tgl_awal',TRUE),$this->input->post('tgl_akhir',TRUE))
            );
        }

        // var_dump($data);
        $data['title'] = "Laporan";
        $this->template->load('template','laporan/index',$data);
    }

    public function cetak_laporan(){
        $this->load->library('Pdf');
        $data = array(
            'jenis'         => set_value('jenis',$this->input->get('jenis',TRUE)), 
            'tgl_awal'    => set_value('tgl_awal',$this->input->get('tgl_awal',TRUE)), 
            'tgl_akhir'     => set_value('tgl_akhir',$this->input->get('tgl_akhir',TRUE))
        );
        $jenis = $this->input->get('jenis',TRUE);
        // var_dump($data);
        if($jenis == 1){
            $data['result'] = $this->Laporan_model->registrasi_pelanggan($data);
            $this->load->view('laporan/registrasi_pelanggan_pdf',$data);
        }elseif($jenis == 2){
            $data['result'] = $this->Laporan_model->booking($data);
            $this->load->view('laporan/booking_pdf',$data);
        }elseif($jenis == 3){
            $data['result'] = $this->Laporan_model->keuangan($data);
            $this->load->view('laporan/keuangan_pdf',$data);
        }
    }

}

/* End of file Laporan.php */
/* Location: ./application/controllers/Laporan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator */
/* Modified by Mohamad_Sopian Codeigniter CRUD Generator 2021-06-23 18:54:16 */
/* http://harviacode.com */