<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    function registrasi_pelanggan($r)
    {
        $this->db->select('
            pelanggan.no_ktp,
            pelanggan.nama,
            pelanggan.alamat,
            pelanggan.tgl_lahir,
            pelanggan.no_telp,
            pelanggan.tgl_daftar,
            tbl_user.email
            ');
         $this->db->join('tbl_user', 'tbl_user.id_users = pelanggan.id_pelanggan','left');
        $this->db->where('pelanggan.tgl_daftar >= ', $r['tgl_awal']);
        $this->db->where('pelanggan.tgl_daftar <= ', $r['tgl_akhir']);
        return $this->db->get('pelanggan')->result();
    }

    function booking($r)
    {
        $this->db->select('
            booking.id_booking,
            booking.id_pelanggan,
            booking.id_ballroom,
            booking.tgl_booking,
            booking.tgl_event,
            booking.deposit,
            ballroom.nama_ballroom,
            pelanggan.nama AS nama_pelanggan,
            booking.keterangan,
            booking.total_bayar,
            ballroom.keterangan as deskripsi_ballroom,
            ballroom.kapasitas,
            pelanggan.no_ktp,
            pelanggan.alamat,
            pelanggan.tgl_lahir,
            pelanggan.no_telp,
            pelanggan.tgl_daftar
        ');
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = booking.id_pelanggan');
        $this->db->join('ballroom', 'ballroom.id_ballroom = booking.id_ballroom');
        $this->db->where('booking.tgl_booking >= ', $r['tgl_awal']);
        $this->db->where('booking.tgl_booking <= ', $r['tgl_akhir']);
        return $this->db->get('booking')->result();
    }

    function keuangan($r)
    {
        $this->db->select('
            booking.id_booking,
            booking.id_pelanggan,
            booking.id_ballroom,
            booking.tgl_booking,
            booking.tgl_event,
            booking.deposit,
            ballroom.nama_ballroom,
            pelanggan.nama AS nama_pelanggan,
            booking.keterangan,
            booking.total_bayar,
            ballroom.keterangan as deskripsi_ballroom,
            ballroom.kapasitas,
            ballroom.harga,
            pelanggan.no_ktp,
            pelanggan.alamat,
            pelanggan.tgl_lahir,
            pelanggan.no_telp,
            pelanggan.tgl_daftar
        ');
        $this->db->join('pelanggan', 'pelanggan.id_pelanggan = booking.id_pelanggan');
        $this->db->join('ballroom', 'ballroom.id_ballroom = booking.id_ballroom');
        $this->db->where('booking.status', '1');
        $this->db->where('booking.tgl_booking >= ', $r['tgl_awal']);
        $this->db->where('booking.tgl_booking <= ', $r['tgl_akhir']);
        return $this->db->get('booking')->result();
    }

}

/* End of file Laporan_model.php */
/* Location: ./application/models/Laporan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator */
/* Modified by Mohamad_Sopian Codeigniter CRUD Generator 2021-06-23 18:44:55 */
/* http://harviacode.com */